services:
  frontend:
    image: shivam0023/nova-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://43.205.232.98:8000
    depends_on:
      - backend

  backend:
    image: shivam0023/nova-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:shivam1747@database-1.cx6ckeqs8iej.ap-south-1.rds.amazonaws.com:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nova_commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
